In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle
import json
import pandas as pd
import joblib

# Load the saved model
model = load_model('/content/mbahlaptop_quantile_V0.1.h5')



In [ ]:
# Define the same numerical and categorical features used during training
numeric_features = ['Ram', 'Storage', 'display_size', 'resolution_width', 'resolution_height']
categorical_features = ['processor','brand', 'Storage_type', 'GPU', 'OS']

# Example new data (replace with your actual new data)
new_data = pd.DataFrame({
    'Ram': [8],
    'Storage': [512],
    'display_size': [15.6],
    'resolution_width': [1920],
    'resolution_height': [1080],
    'brand': ['Asus'],
    'processor': ['10th Gen Intel Core i5 10300H'],
    'Ram_type': ['DDR4'],
    'Storage_type': ['SSD'],
    'GPU': ['NVIDIA GeForce GTX 1650'],
    'OS': ['Windows 11 OS']
})

new_data = pd.DataFrame(new_data)

numeric_preprocessor = joblib.load('numeric_preprocessor.pkl')

X_numeric = numeric_preprocessor.fit_transform(new_data[numeric_features])
X_numeric = pd.DataFrame(X_numeric, columns=numeric_features)


categorical_vocabularies = {}

# Reload each feature's vocabulary
for feature in categorical_features:
    with open(f'{feature}_vocabulary.json', 'r') as f:
        vocabulary = json.load(f)
        categorical_vocabularies[feature] = vocabulary



In [ ]:
X_categorical_encoded = []
for feature in categorical_features:
    vocabulary = categorical_vocabularies[feature]
    encoded = np.zeros(len(vocabulary))  # Initialize encoding as all zeros

    # Access the feature's value and split it into components
    value = new_data[feature][0]  # Get the single value as a string
    components = value.lower().split(" ")  # Split the string into components (case-insensitive)

    # Encode based on vocabulary
    for component in components:
        if component in vocabulary:
            encoded[vocabulary.index(component)] = 1  # Set the corresponding index to 1

    X_categorical_encoded.append(encoded)

X_categorical_encoded


[array([0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [ ]:
X_categorical = np.hstack([encoded.reshape(1, -1) for encoded in X_categorical_encoded])

# Combine numeric and categorical features
X_processed = np.hstack([X_numeric, X_categorical])  # Combine horizontally

In [ ]:
quantiles = [0.25, 0.5, 0.75]

In [ ]:

# # # Make a prediction
# predicted_price = model.predict(X_processed)
# print("Predicted price:", predicted_price )

In [ ]:
# Quantile regression predict
y_pred = model.predict(X_processed)
intervals = pd.DataFrame(y_pred, columns=[f"Quantile {q}" for q in quantiles])
print(intervals)



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
Predicted price: [[10583237. 11066178. 11609217.]]
